# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXjaKq_pmk3ZPfNuwNqPsxjO1kITTmYe
"""

import pandas as pd

# Excel faylini ochish
file_path = '613.xlsx'  # mavjud Excel fayl manzili
df = pd.read_excel(file_path)

# Ma'lumotlarni tartiblash (masalan, 'Name' ustuni bo'yicha o'sish tartibida)
sorted_df = df.sort_values(by='To‘liq ismi')

# Tartiblangan ma'lumotlarni yangi Excel faylga saqlash
sorted_df.to_excel('613 yangi.xlsx', index=False)